# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/mmx/s9081/extract-proprietary.sh

# Prebuilt libraries 
PRODUCT_COPY_proprietary += \
    vendor/mmx/s9081/proprietary/lib/egl/libEGL_mtk.so:system/lib/egl/libEGL_mtk.so \
    vendor/mmx/s9081/proprietary/lib/egl/libGLESv1_CM_mtk.so:system/lib/egl/libGLESv1_CM_mtk.so \
    vendor/mmx/s9081/proprietary/lib/egl/libGLESv2_mtk.so:system/lib/egl/libGLESv2_mtk.so \
    vendor/mmx/s9081/proprietary/lib/hw/gralloc.mt6577.so:system/lib/hw/gralloc.mt6577.so \
    vendor/mmx/s9081/proprietary/lib/libBLPP.so:system/lib/libBLPP.so \
    vendor/mmx/s9081/proprietary/lib/libglslcompiler.so:system/lib/libglslcompiler.so \
    vendor/mmx/s9081/proprietary/lib/libIMGegl.so:system/lib/libIMGegl.so \
    vendor/mmx/s9081/proprietary/lib/libpvr2d.so:system/lib/libpvr2d.so \
    vendor/mmx/s9081/proprietary/lib/libpvrANDROID_WSEGL.so:system/lib/libpvrANDROID_WSEGL.so \
    vendor/mmx/s9081/proprietary/lib/libPVRScopeServices.so:system/lib/libPVRScopeServices.so \
    vendor/mmx/s9081/proprietary/lib/libsrv_init.so:system/lib/libsrv_init.so \
    vendor/mmx/s9081/proprietary/lib/libsrv_um.so:system/lib/libsrv_um.so \
    vendor/mmx/s9081/proprietary/lib/libusc.so:system/lib/libusc.so \
    vendor/mmx/s9081/proprietary/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so \
    vendor/mmx/s9081/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/mmx/s9081/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
     
    
# RIL
PRODUCT_COPY_proprietary += \
    vendor/mmx/s9081/proprietary/lib/mtk-ril.so:system/lib/mtk-ril.so \
    vendor/mmx/s9081/proprietary/lib/mtk-ril3.so:system/lib/mtk-ril3.so \
    vendor/mmx/s9081/proprietary/lib/librilmtk.so:system/lib/librilmtk.so \
    vendor/mmx/s9081/proprietary/lib/libril3mtk.so:system/lib/libril3mtk.so
    
 
# Bluetooth
PRODUCT_COPY_proprietary += \
    vendor/mmx/s9081/proprietary/lib/libmtka2dp.so:system/lib/libmtka2dp.so \
    
# Sensors
PRODUCT_COPY_FILES += \
    vendor/mmx/s9081/proprietary/lib/hw/sensors.mt6577.so:system/lib/hw/sensors.mt6577.so \

# Keychars & keylayouts
PRODUCT_COPY_FILES += \
    vendor/mmx/s9081/proprietary/usr/keychars/mtk-kpd.kcm:system/usr/keychars/mtk-kpd.kcm \
    vendor/mmx/s9081/proprietary/usr/keychars/Virtual.kcm:system/usr/keychars/Virtual.kcm \
    vendor/mmx/s9081/proprietary/usr/keylayout/ACCDET.kl:system/usr/keylayout/ACCDET.kl \
    vendor/mmx/s9081/proprietary/usr/keylayout/mtk-kpd.kl:system/usr/keylayout/mtk-kpd.kl \
    vendor/mmx/s9081/proprietary/usr/keylayout/Vendor_05ac_Product_0239.kl:system/usr/keylayout/Vendor_05ac_Product_0239.kl \
    vendor/mmx/s9081/proprietary/usr/keylayout/Vendor_22b8_Product_093d.kl:system/usr/keylayout/Vendor_22b8_Product_093d.kl \
    vendor/mmx/s9081/proprietary/usr/keylayout/Vendor_045e_Product_028e.kl:system/usr/keylayout/Vendor_045e_Product_028e.kl \
    vendor/mmx/s9081/proprietary/usr/keylayout/Vendor_046d_Product_c216.kl:system/usr/keylayout/Vendor_046d_Product_c216.kl \
    vendor/mmx/s9081/proprietary/usr/keylayout/Vendor_046d_Product_c294.kl:system/usr/keylayout/Vendor_046d_Product_c294.kl \
    vendor/mmx/s9081/proprietary/usr/keylayout/Vendor_046d_Product_c299.kl:system/usr/keylayout/Vendor_046d_Product_c299.kl \
    vendor/mmx/s9081/proprietary/usr/keylayout/Vendor_046d_Product_c532.kl:system/usr/keylayout/Vendor_046d_Product_c532.kl \
    vendor/mmx/s9081/proprietary/usr/keylayout/Vendor_054c_Product_0268.kl:system/usr/keylayout/Vendor_054c_Product_0268.kl \
    

